apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilender-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: https://github.com/vksuktha/argo-app-ilender-kustomize
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
