apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilender-loanprocessor

  labels:
    app: ilender-application
    subname: loanprocessor
spec:
  selector:
    matchLabels:
      app: ilender-application
      subname: loanprocessor
  replicas: 1
  template:
    metadata:
      labels:
        app: ilender-application
        subname: loanprocessor
    spec:
      containers:
        - name: container-loanprocessor
          image: "gandigit/ilender-loanprocessor-ocp-logs:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9073
              protocol: TCP
            - name: https
              containerPort: 8082
          envFrom:
            - configMapRef:
                name: ilender-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ilender-loanprocessor
  labels:
    app: ilender-application
    subname: loanprocessor
spec:
  type: LoadBalancer
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
  selector:
    app: ilender-application
    subname: loanprocessor
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ilender-loanprocessor
  labels:
    app: ilender-application
    subname: loanprocessor
spec:
  path: /
  to:
    kind: Service
    name: ilender-loanprocessor
    weight: 100
  port:
    targetPort: my-http
